# Generated by Django 4.2.15 on 2024-08-18 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0020_alter_insuree_card_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblInsuree',
            fields=[
                ('insuree_id', models.AutoField(db_column='InsureeID', primary_key=True, serialize=False)),
                ('chfid', models.CharField(blank=True, db_column='CHFID', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
            options={
                'db_table': 'tblInsuree',
            },
        ),
        migrations.AlterField(
            model_name='insuree',
            name='chf_id',
            field=models.CharField(blank=True, db_column='CHFID', max_length=6, null=True),
        ),
    ]
